#!/usr/bin/env bash
# error 404 fix

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo service nginx start
sed -i '/listen \[::\]:80 default_server;/a\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sed -i '/TGUlwu4 permanent;$/a\\terror_page 404 /custom_404.html;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" >/var/www/html/custom_404.html
sudo service nginx restart
