#!/usr/bin/env bash
# displays a list of currently running processes
# ps - current process
# -a - Select all processes except both session leaders
# -u - display user ID
# -x - date start procces
# -f - full-format listing

ps -auxf
