#!/usr/bin/env bash
# This script gives you information about the school file

sch="school"

if [ -e $sch ]
then
    echo "$sch file exists"

    if [ -s $sch ]
    then
	echo "$sch file is not empty"
    else
	echo "$sch file is empty"
    fi

    if [ -f $sch ]
    then
	echo "$sch is a regular file"
    fi
else
    echo "$sch file does not exist"
fi
