#!/usr/bin/env bash
# configure apache to run on port 8080 and display Hello Holberton
# when querying the root of it

echo "ServerName 127.0.0.1" >> /etc/apache2/apache2.conf
echo "Listen 8080" >> /etc/apache2/ports.conf
sed -i "s/<VirtualHost /<VirtualHost *:8080 /" /etc/apache2/sites-enabled/000-default.conf
sudo service apache2 restart
